# Generated by Django 5.2.8 on 2025-11-21 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.IntegerField()),
                ('baths', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sqft', models.IntegerField()),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('amenities', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Applicant', 'Applicant'), ('Approved', 'Approved'), ('Active', 'Active'), ('Past', 'Past'), ('Eviction Pending', 'Eviction Pending')], default='Applicant', max_length=50)),
                ('property_unit', models.CharField(max_length=255)),
                ('lease_start', models.DateField(blank=True, null=True)),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('background_check_status', models.CharField(blank=True, max_length=50, null=True)),
                ('application_data', models.JSONField(blank=True, null=True)),
                ('lease_status', models.CharField(blank=True, max_length=50, null=True)),
                ('signed_lease_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Failed', 'Failed')], max_length=50)),
                ('type', models.CharField(choices=[('Rent', 'Rent'), ('Late Fee', 'Late Fee'), ('Deposit', 'Deposit'), ('Application Fee', 'Application Fee')], max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('images', models.JSONField(blank=True, default=list)),
                ('updates', models.JSONField(blank=True, default=list)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_attachments', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('generated_content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('delivery_method', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='api.tenant')),
            ],
        ),
    ]
