# Generated by Django 5.2.8 on 2025-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
