# Generated by Django 5.2.8 on 2025-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_property_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Lease template content with placeholders like {{tenant_name}}, {{rent_amount}}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='docusign_envelope_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='docusign_signing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='leases/'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='signed_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
