# Generated by Django 5.2.8 on 2025-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_leasetemplate_legaldocument_docusign_envelope_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='income_verification_files',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded income verification file paths'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='photo_id_files',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded photo ID file paths'),
        ),
    ]
